# Generated by Django 4.2.14 on 2024-08-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_category_image_background_color_category_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos/categoriesIcons/'),
        ),
    ]
