# Generated by Django 4.2.14 on 2024-09-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='Warszawa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='voivodeship',
            field=models.CharField(choices=[('DS', 'Dolnośląskie'), ('KP', 'Kujawsko-Pomorskie'), ('LB', 'Lubelskie'), ('LS', 'Lubuskie'), ('LD', 'Łódzkie'), ('MA', 'Małopolskie'), ('MZ', 'Mazowieckie'), ('OP', 'Opolskie'), ('PK', 'Podkarpackie'), ('PD', 'Podlaskie'), ('PM', 'Pomorskie'), ('SL', 'Śląskie'), ('SK', 'Świetokrzyskie'), ('WM', 'Warmińsko-Mazurskie'), ('WP', 'Wielkopolskie'), ('ZP', 'Zachodniopomorskie')], default='DS', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_path',
            field=models.ImageField(upload_to='photos/categoriesIcons/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
