# Generated by Django 4.2.14 on 2024-09-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_product_city_product_voivodeship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
