# Generated by Django 4.2.14 on 2024-09-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
